name: Continuous Integration

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run htmlhint
      - run: npm run stylelint

  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build
        run: |
          npm init -y
          npm install
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun --collect.staticDistDir="./" --rc-overrides.upload.target=temporary-public-storage --assert.preset=lighthouse:no-pwa

  prettier:
    name: Prettier formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: run Prettier on HTML, CSS, and JS files
        run: |
          npm install -g prettier
          prettier --check "./**/*.{html,css,js}"
